url: https://msspektor.github.io/
enforce_ssl: msspektor.github.io
baseurl: ""

production_url : https://msspektor.github.io

# Site settings
title: Mikhail Spektor
email: mikhail.spektor@upf.edu
description: "Mikhail Spektor is an assistant professor at the Department of Economics and Business, Universitat Pompeu Fabra."

author :
  name : Mikhail Spektor
  email : mikhail@spektor.ch
  github : msspektor
  twitter : SpektorMikhail

# Build settings
markdown: kramdown
permalink: pretty
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md 
  - .gitignore
